
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm ci


COPY . .


RUN npm run build


FROM node:20-alpine 

WORKDIR /usr/src/app


COPY package*.json ./


RUN npm ci --only=production


COPY --from=builder /usr/src/app/public ./


ENV NODE_ENV=production
ENV PORT=3000

EXPOSE $PORT

CMD ["node", "./index.js"]
